# coding: utf-8

import sys
from setuptools import setup, find_packages, find_namespace_packages

NAME = "lifelog"
VERSION = "1.1.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["connexion"]

setup(
    name=NAME,
    version=VERSION,
    description="LifeLog",
    author_email="muenier.elliott@gmail.com",
    url="",
    keywords=["Swagger", "LifeLog"],
    install_requires=REQUIRES,
    packages=find_namespace_packages(include=['lifelog.*']),
    package_data={'': ['openapi/openapi.yaml']},
    include_package_data=True,
    entry_points={
        'console_scripts': ['lifelog=lifelog.main.__main__:main']},
    long_description="""\
    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
    """
)
