# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.event import Event  # noqa: F401,E501
from swagger_server import util


class BloodTest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, element_type: str='event', event_timestamp: datetime=None, event_type: str='blood_test', blood_test_level: float=None, blood_test_type: str=None):  # noqa: E501
        """BloodTest - a model defined in Swagger

        :param element_type: The element_type of this BloodTest.  # noqa: E501
        :type element_type: str
        :param event_timestamp: The event_timestamp of this BloodTest.  # noqa: E501
        :type event_timestamp: datetime
        :param event_type: The event_type of this BloodTest.  # noqa: E501
        :type event_type: str
        :param blood_test_level: The blood_test_level of this BloodTest.  # noqa: E501
        :type blood_test_level: float
        :param blood_test_type: The blood_test_type of this BloodTest.  # noqa: E501
        :type blood_test_type: str
        """
        self.swagger_types = {
            'element_type': str,
            'event_timestamp': datetime,
            'event_type': str,
            'blood_test_level': float,
            'blood_test_type': str
        }

        self.attribute_map = {
            'element_type': 'element_type',
            'event_timestamp': 'event_timestamp',
            'event_type': 'event_type',
            'blood_test_level': 'blood_test_level',
            'blood_test_type': 'blood_test_type'
        }
        self._element_type = element_type
        self._event_timestamp = event_timestamp
        self._event_type = event_type
        self._blood_test_level = blood_test_level
        self._blood_test_type = blood_test_type

    @classmethod
    def from_dict(cls, dikt) -> 'BloodTest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BloodTest of this BloodTest.  # noqa: E501
        :rtype: BloodTest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def element_type(self) -> str:
        """Gets the element_type of this BloodTest.


        :return: The element_type of this BloodTest.
        :rtype: str
        """
        return self._element_type

    @element_type.setter
    def element_type(self, element_type: str):
        """Sets the element_type of this BloodTest.


        :param element_type: The element_type of this BloodTest.
        :type element_type: str
        """

        self._element_type = element_type

    @property
    def event_timestamp(self) -> datetime:
        """Gets the event_timestamp of this BloodTest.


        :return: The event_timestamp of this BloodTest.
        :rtype: datetime
        """
        return self._event_timestamp

    @event_timestamp.setter
    def event_timestamp(self, event_timestamp: datetime):
        """Sets the event_timestamp of this BloodTest.


        :param event_timestamp: The event_timestamp of this BloodTest.
        :type event_timestamp: datetime
        """
        if event_timestamp is None:
            raise ValueError("Invalid value for `event_timestamp`, must not be `None`")  # noqa: E501

        self._event_timestamp = event_timestamp

    @property
    def event_type(self) -> str:
        """Gets the event_type of this BloodTest.


        :return: The event_type of this BloodTest.
        :rtype: str
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type: str):
        """Sets the event_type of this BloodTest.


        :param event_type: The event_type of this BloodTest.
        :type event_type: str
        """

        self._event_type = event_type

    @property
    def blood_test_level(self) -> float:
        """Gets the blood_test_level of this BloodTest.

        ketonemia: quantity in [mmol/L], blood_sugar: quantity in [mg/dL]  # noqa: E501

        :return: The blood_test_level of this BloodTest.
        :rtype: float
        """
        return self._blood_test_level

    @blood_test_level.setter
    def blood_test_level(self, blood_test_level: float):
        """Sets the blood_test_level of this BloodTest.

        ketonemia: quantity in [mmol/L], blood_sugar: quantity in [mg/dL]  # noqa: E501

        :param blood_test_level: The blood_test_level of this BloodTest.
        :type blood_test_level: float
        """
        if blood_test_level is None:
            raise ValueError("Invalid value for `blood_test_level`, must not be `None`")  # noqa: E501

        self._blood_test_level = blood_test_level

    @property
    def blood_test_type(self) -> str:
        """Gets the blood_test_type of this BloodTest.


        :return: The blood_test_type of this BloodTest.
        :rtype: str
        """
        return self._blood_test_type

    @blood_test_type.setter
    def blood_test_type(self, blood_test_type: str):
        """Sets the blood_test_type of this BloodTest.


        :param blood_test_type: The blood_test_type of this BloodTest.
        :type blood_test_type: str
        """
        allowed_values = ["ketonemia", "blood_sugar"]  # noqa: E501
        if blood_test_type not in allowed_values:
            raise ValueError(
                "Invalid value for `blood_test_type` ({0}), must be one of {1}"
                .format(blood_test_type, allowed_values)
            )

        self._blood_test_type = blood_test_type
