# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.element_base import Element  # noqa: F401,E501
from swagger_server import util


class DayDescriptor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, element_type: str='day_descriptor', element_uuid: str=None, element_created_at: datetime=None, element_updated_at: datetime=None, day_descriptor_date: date=None, day_descriptor_type: str=None):  # noqa: E501
        """DayDescriptor - a model defined in Swagger

        :param element_type: The element_type of this DayDescriptor.  # noqa: E501
        :type element_type: str
        :param element_uuid: The element_uuid of this DayDescriptor.  # noqa: E501
        :type element_uuid: str
        :param element_created_at: The element_created_at of this DayDescriptor.  # noqa: E501
        :type element_created_at: datetime
        :param element_updated_at: The element_updated_at of this DayDescriptor.  # noqa: E501
        :type element_updated_at: datetime
        :param day_descriptor_date: The day_descriptor_date of this DayDescriptor.  # noqa: E501
        :type day_descriptor_date: date
        :param day_descriptor_type: The day_descriptor_type of this DayDescriptor.  # noqa: E501
        :type day_descriptor_type: str
        """
        self.swagger_types = {
            'element_type': str,
            'element_uuid': str,
            'element_created_at': datetime,
            'element_updated_at': datetime,
            'day_descriptor_date': date,
            'day_descriptor_type': str
        }

        self.attribute_map = {
            'element_type': 'element_type',
            'element_uuid': 'element_uuid',
            'element_created_at': 'element_created_at',
            'element_updated_at': 'element_updated_at',
            'day_descriptor_date': 'day_descriptor_date',
            'day_descriptor_type': 'day_descriptor_type'
        }
        self._element_type = element_type
        self._element_uuid = element_uuid
        self._element_created_at = element_created_at
        self._element_updated_at = element_updated_at
        self._day_descriptor_date = day_descriptor_date
        self._day_descriptor_type = day_descriptor_type

    @classmethod
    def from_dict(cls, dikt) -> 'DayDescriptor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DayDescriptor of this DayDescriptor.  # noqa: E501
        :rtype: DayDescriptor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def element_type(self) -> str:
        """Gets the element_type of this DayDescriptor.


        :return: The element_type of this DayDescriptor.
        :rtype: str
        """
        return self._element_type

    @element_type.setter
    def element_type(self, element_type: str):
        """Sets the element_type of this DayDescriptor.


        :param element_type: The element_type of this DayDescriptor.
        :type element_type: str
        """

        self._element_type = element_type

    @property
    def element_uuid(self) -> str:
        """Gets the element_uuid of this DayDescriptor.


        :return: The element_uuid of this DayDescriptor.
        :rtype: str
        """
        return self._element_uuid

    @element_uuid.setter
    def element_uuid(self, element_uuid: str):
        """Sets the element_uuid of this DayDescriptor.


        :param element_uuid: The element_uuid of this DayDescriptor.
        :type element_uuid: str
        """

        self._element_uuid = element_uuid

    @property
    def element_created_at(self) -> datetime:
        """Gets the element_created_at of this DayDescriptor.


        :return: The element_created_at of this DayDescriptor.
        :rtype: datetime
        """
        return self._element_created_at

    @element_created_at.setter
    def element_created_at(self, element_created_at: datetime):
        """Sets the element_created_at of this DayDescriptor.


        :param element_created_at: The element_created_at of this DayDescriptor.
        :type element_created_at: datetime
        """

        self._element_created_at = element_created_at

    @property
    def element_updated_at(self) -> datetime:
        """Gets the element_updated_at of this DayDescriptor.


        :return: The element_updated_at of this DayDescriptor.
        :rtype: datetime
        """
        return self._element_updated_at

    @element_updated_at.setter
    def element_updated_at(self, element_updated_at: datetime):
        """Sets the element_updated_at of this DayDescriptor.


        :param element_updated_at: The element_updated_at of this DayDescriptor.
        :type element_updated_at: datetime
        """

        self._element_updated_at = element_updated_at

    @property
    def day_descriptor_date(self) -> date:
        """Gets the day_descriptor_date of this DayDescriptor.


        :return: The day_descriptor_date of this DayDescriptor.
        :rtype: date
        """
        return self._day_descriptor_date

    @day_descriptor_date.setter
    def day_descriptor_date(self, day_descriptor_date: date):
        """Sets the day_descriptor_date of this DayDescriptor.


        :param day_descriptor_date: The day_descriptor_date of this DayDescriptor.
        :type day_descriptor_date: date
        """
        if day_descriptor_date is None:
            raise ValueError("Invalid value for `day_descriptor_date`, must not be `None`")  # noqa: E501

        self._day_descriptor_date = day_descriptor_date

    @property
    def day_descriptor_type(self) -> str:
        """Gets the day_descriptor_type of this DayDescriptor.


        :return: The day_descriptor_type of this DayDescriptor.
        :rtype: str
        """
        return self._day_descriptor_type

    @day_descriptor_type.setter
    def day_descriptor_type(self, day_descriptor_type: str):
        """Sets the day_descriptor_type of this DayDescriptor.


        :param day_descriptor_type: The day_descriptor_type of this DayDescriptor.
        :type day_descriptor_type: str
        """

        self._day_descriptor_type = day_descriptor_type
