# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Element(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, element_type: str=None, element_uuid: str=None, element_created_at: datetime=None, element_updated_at: datetime=None):  # noqa: E501
        """Element - a model defined in Swagger

        :param element_type: The element_type of this Element.  # noqa: E501
        :type element_type: str
        :param element_uuid: The element_uuid of this Element.  # noqa: E501
        :type element_uuid: str
        :param element_created_at: The element_created_at of this Element.  # noqa: E501
        :type element_created_at: datetime
        :param element_updated_at: The element_updated_at of this Element.  # noqa: E501
        :type element_updated_at: datetime
        """
        self.swagger_types = {
            'element_type': str,
            'element_uuid': str,
            'element_created_at': datetime,
            'element_updated_at': datetime
        }

        self.attribute_map = {
            'element_type': 'element_type',
            'element_uuid': 'element_uuid',
            'element_created_at': 'element_created_at',
            'element_updated_at': 'element_updated_at'
        }
        self._element_type = element_type
        self._element_uuid = element_uuid
        self._element_created_at = element_created_at
        self._element_updated_at = element_updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Element':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Element of this Element.  # noqa: E501
        :rtype: Element
        """
        return util.deserialize_model(dikt, cls)

    @property
    def element_type(self) -> str:
        """Gets the element_type of this Element.


        :return: The element_type of this Element.
        :rtype: str
        """
        return self._element_type

    @element_type.setter
    def element_type(self, element_type: str):
        """Sets the element_type of this Element.


        :param element_type: The element_type of this Element.
        :type element_type: str
        """

        self._element_type = element_type

    @property
    def element_uuid(self) -> str:
        """Gets the element_uuid of this Element.


        :return: The element_uuid of this Element.
        :rtype: str
        """
        return self._element_uuid

    @element_uuid.setter
    def element_uuid(self, element_uuid: str):
        """Sets the element_uuid of this Element.


        :param element_uuid: The element_uuid of this Element.
        :type element_uuid: str
        """

        self._element_uuid = element_uuid

    @property
    def element_created_at(self) -> datetime:
        """Gets the element_created_at of this Element.


        :return: The element_created_at of this Element.
        :rtype: datetime
        """
        return self._element_created_at

    @element_created_at.setter
    def element_created_at(self, element_created_at: datetime):
        """Sets the element_created_at of this Element.


        :param element_created_at: The element_created_at of this Element.
        :type element_created_at: datetime
        """

        self._element_created_at = element_created_at

    @property
    def element_updated_at(self) -> datetime:
        """Gets the element_updated_at of this Element.


        :return: The element_updated_at of this Element.
        :rtype: datetime
        """
        return self._element_updated_at

    @element_updated_at.setter
    def element_updated_at(self, element_updated_at: datetime):
        """Sets the element_updated_at of this Element.


        :param element_updated_at: The element_updated_at of this Element.
        :type element_updated_at: datetime
        """

        self._element_updated_at = element_updated_at
