# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.element import Element  # noqa: F401,E501
from swagger_server import util


class Period(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, element_type: str='period', element_uuid: str=None, element_created_at: datetime=None, element_updated_at: datetime=None, period_range: str=None, period_type: str=None, period_description: str=''):  # noqa: E501
        """Period - a model defined in Swagger

        :param element_type: The element_type of this Period.  # noqa: E501
        :type element_type: str
        :param element_uuid: The element_uuid of this Period.  # noqa: E501
        :type element_uuid: str
        :param element_created_at: The element_created_at of this Period.  # noqa: E501
        :type element_created_at: datetime
        :param element_updated_at: The element_updated_at of this Period.  # noqa: E501
        :type element_updated_at: datetime
        :param period_range: The period_range of this Period.  # noqa: E501
        :type period_range: str
        :param period_type: The period_type of this Period.  # noqa: E501
        :type period_type: str
        :param period_description: The period_description of this Period.  # noqa: E501
        :type period_description: str
        """
        self.swagger_types = {
            'element_type': str,
            'element_uuid': str,
            'element_created_at': datetime,
            'element_updated_at': datetime,
            'period_range': str,
            'period_type': str,
            'period_description': str
        }

        self.attribute_map = {
            'element_type': 'element_type',
            'element_uuid': 'element_uuid',
            'element_created_at': 'element_created_at',
            'element_updated_at': 'element_updated_at',
            'period_range': 'period_range',
            'period_type': 'period_type',
            'period_description': 'period_description'
        }
        self._element_type = element_type
        self._element_uuid = element_uuid
        self._element_created_at = element_created_at
        self._element_updated_at = element_updated_at
        self._period_range = period_range
        self._period_type = period_type
        self._period_description = period_description

    @classmethod
    def from_dict(cls, dikt) -> 'Period':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Period of this Period.  # noqa: E501
        :rtype: Period
        """
        return util.deserialize_model(dikt, cls)

    @property
    def element_type(self) -> str:
        """Gets the element_type of this Period.


        :return: The element_type of this Period.
        :rtype: str
        """
        return self._element_type

    @element_type.setter
    def element_type(self, element_type: str):
        """Sets the element_type of this Period.


        :param element_type: The element_type of this Period.
        :type element_type: str
        """

        self._element_type = element_type

    @property
    def element_uuid(self) -> str:
        """Gets the element_uuid of this Period.


        :return: The element_uuid of this Period.
        :rtype: str
        """
        return self._element_uuid

    @element_uuid.setter
    def element_uuid(self, element_uuid: str):
        """Sets the element_uuid of this Period.


        :param element_uuid: The element_uuid of this Period.
        :type element_uuid: str
        """

        self._element_uuid = element_uuid

    @property
    def element_created_at(self) -> datetime:
        """Gets the element_created_at of this Period.


        :return: The element_created_at of this Period.
        :rtype: datetime
        """
        return self._element_created_at

    @element_created_at.setter
    def element_created_at(self, element_created_at: datetime):
        """Sets the element_created_at of this Period.


        :param element_created_at: The element_created_at of this Period.
        :type element_created_at: datetime
        """

        self._element_created_at = element_created_at

    @property
    def element_updated_at(self) -> datetime:
        """Gets the element_updated_at of this Period.


        :return: The element_updated_at of this Period.
        :rtype: datetime
        """
        return self._element_updated_at

    @element_updated_at.setter
    def element_updated_at(self, element_updated_at: datetime):
        """Sets the element_updated_at of this Period.


        :param element_updated_at: The element_updated_at of this Period.
        :type element_updated_at: datetime
        """

        self._element_updated_at = element_updated_at

    @property
    def period_range(self) -> str:
        """Gets the period_range of this Period.


        :return: The period_range of this Period.
        :rtype: str
        """
        return self._period_range

    @period_range.setter
    def period_range(self, period_range: str):
        """Sets the period_range of this Period.


        :param period_range: The period_range of this Period.
        :type period_range: str
        """
        if period_range is None:
            raise ValueError("Invalid value for `period_range`, must not be `None`")  # noqa: E501

        self._period_range = period_range

    @property
    def period_type(self) -> str:
        """Gets the period_type of this Period.


        :return: The period_type of this Period.
        :rtype: str
        """
        return self._period_type

    @period_type.setter
    def period_type(self, period_type: str):
        """Sets the period_type of this Period.


        :param period_type: The period_type of this Period.
        :type period_type: str
        """

        self._period_type = period_type

    @property
    def period_description(self) -> str:
        """Gets the period_description of this Period.


        :return: The period_description of this Period.
        :rtype: str
        """
        return self._period_description

    @period_description.setter
    def period_description(self, period_description: str):
        """Sets the period_description of this Period.


        :param period_description: The period_description of this Period.
        :type period_description: str
        """

        self._period_description = period_description
