# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.event import Event  # noqa: F401,E501
from swagger_server import util


class Pill(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, element_type: str='event', event_timestamp: datetime=None, event_type: str='pill', pill_type: str=None, pill_name: str=None):  # noqa: E501
        """Pill - a model defined in Swagger

        :param element_type: The element_type of this Pill.  # noqa: E501
        :type element_type: str
        :param event_timestamp: The event_timestamp of this Pill.  # noqa: E501
        :type event_timestamp: datetime
        :param event_type: The event_type of this Pill.  # noqa: E501
        :type event_type: str
        :param pill_type: The pill_type of this Pill.  # noqa: E501
        :type pill_type: str
        :param pill_name: The pill_name of this Pill.  # noqa: E501
        :type pill_name: str
        """
        self.swagger_types = {
            'element_type': str,
            'event_timestamp': datetime,
            'event_type': str,
            'pill_type': str,
            'pill_name': str
        }

        self.attribute_map = {
            'element_type': 'element_type',
            'event_timestamp': 'event_timestamp',
            'event_type': 'event_type',
            'pill_type': 'pill_type',
            'pill_name': 'pill_name'
        }
        self._element_type = element_type
        self._event_timestamp = event_timestamp
        self._event_type = event_type
        self._pill_type = pill_type
        self._pill_name = pill_name

    @classmethod
    def from_dict(cls, dikt) -> 'Pill':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pill of this Pill.  # noqa: E501
        :rtype: Pill
        """
        return util.deserialize_model(dikt, cls)

    @property
    def element_type(self) -> str:
        """Gets the element_type of this Pill.


        :return: The element_type of this Pill.
        :rtype: str
        """
        return self._element_type

    @element_type.setter
    def element_type(self, element_type: str):
        """Sets the element_type of this Pill.


        :param element_type: The element_type of this Pill.
        :type element_type: str
        """

        self._element_type = element_type

    @property
    def event_timestamp(self) -> datetime:
        """Gets the event_timestamp of this Pill.


        :return: The event_timestamp of this Pill.
        :rtype: datetime
        """
        return self._event_timestamp

    @event_timestamp.setter
    def event_timestamp(self, event_timestamp: datetime):
        """Sets the event_timestamp of this Pill.


        :param event_timestamp: The event_timestamp of this Pill.
        :type event_timestamp: datetime
        """
        if event_timestamp is None:
            raise ValueError("Invalid value for `event_timestamp`, must not be `None`")  # noqa: E501

        self._event_timestamp = event_timestamp

    @property
    def event_type(self) -> str:
        """Gets the event_type of this Pill.


        :return: The event_type of this Pill.
        :rtype: str
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type: str):
        """Sets the event_type of this Pill.


        :param event_type: The event_type of this Pill.
        :type event_type: str
        """

        self._event_type = event_type

    @property
    def pill_type(self) -> str:
        """Gets the pill_type of this Pill.


        :return: The pill_type of this Pill.
        :rtype: str
        """
        return self._pill_type

    @pill_type.setter
    def pill_type(self, pill_type: str):
        """Sets the pill_type of this Pill.


        :param pill_type: The pill_type of this Pill.
        :type pill_type: str
        """
        if pill_type is None:
            raise ValueError("Invalid value for `pill_type`, must not be `None`")  # noqa: E501

        self._pill_type = pill_type

    @property
    def pill_name(self) -> str:
        """Gets the pill_name of this Pill.


        :return: The pill_name of this Pill.
        :rtype: str
        """
        return self._pill_name

    @pill_name.setter
    def pill_name(self, pill_name: str):
        """Sets the pill_name of this Pill.


        :param pill_name: The pill_name of this Pill.
        :type pill_name: str
        """
        if pill_name is None:
            raise ValueError("Invalid value for `pill_name`, must not be `None`")  # noqa: E501

        self._pill_name = pill_name
