# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.event import Event  # noqa: F401,E501
from swagger_server import util


class Weigh(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, element_type: str='event', event_timestamp: datetime=None, event_type: str='weigh', weigh_heaviness: float=None):  # noqa: E501
        """Weigh - a model defined in Swagger

        :param element_type: The element_type of this Weigh.  # noqa: E501
        :type element_type: str
        :param event_timestamp: The event_timestamp of this Weigh.  # noqa: E501
        :type event_timestamp: datetime
        :param event_type: The event_type of this Weigh.  # noqa: E501
        :type event_type: str
        :param weigh_heaviness: The weigh_heaviness of this Weigh.  # noqa: E501
        :type weigh_heaviness: float
        """
        self.swagger_types = {
            'element_type': str,
            'event_timestamp': datetime,
            'event_type': str,
            'weigh_heaviness': float
        }

        self.attribute_map = {
            'element_type': 'element_type',
            'event_timestamp': 'event_timestamp',
            'event_type': 'event_type',
            'weigh_heaviness': 'weigh_heaviness'
        }
        self._element_type = element_type
        self._event_timestamp = event_timestamp
        self._event_type = event_type
        self._weigh_heaviness = weigh_heaviness

    @classmethod
    def from_dict(cls, dikt) -> 'Weigh':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Weigh of this Weigh.  # noqa: E501
        :rtype: Weigh
        """
        return util.deserialize_model(dikt, cls)

    @property
    def element_type(self) -> str:
        """Gets the element_type of this Weigh.


        :return: The element_type of this Weigh.
        :rtype: str
        """
        return self._element_type

    @element_type.setter
    def element_type(self, element_type: str):
        """Sets the element_type of this Weigh.


        :param element_type: The element_type of this Weigh.
        :type element_type: str
        """

        self._element_type = element_type

    @property
    def event_timestamp(self) -> datetime:
        """Gets the event_timestamp of this Weigh.


        :return: The event_timestamp of this Weigh.
        :rtype: datetime
        """
        return self._event_timestamp

    @event_timestamp.setter
    def event_timestamp(self, event_timestamp: datetime):
        """Sets the event_timestamp of this Weigh.


        :param event_timestamp: The event_timestamp of this Weigh.
        :type event_timestamp: datetime
        """
        if event_timestamp is None:
            raise ValueError("Invalid value for `event_timestamp`, must not be `None`")  # noqa: E501

        self._event_timestamp = event_timestamp

    @property
    def event_type(self) -> str:
        """Gets the event_type of this Weigh.


        :return: The event_type of this Weigh.
        :rtype: str
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type: str):
        """Sets the event_type of this Weigh.


        :param event_type: The event_type of this Weigh.
        :type event_type: str
        """

        self._event_type = event_type

    @property
    def weigh_heaviness(self) -> float:
        """Gets the weigh_heaviness of this Weigh.

        quantity in [g]  # noqa: E501

        :return: The weigh_heaviness of this Weigh.
        :rtype: float
        """
        return self._weigh_heaviness

    @weigh_heaviness.setter
    def weigh_heaviness(self, weigh_heaviness: float):
        """Sets the weigh_heaviness of this Weigh.

        quantity in [g]  # noqa: E501

        :param weigh_heaviness: The weigh_heaviness of this Weigh.
        :type weigh_heaviness: float
        """
        if weigh_heaviness is None:
            raise ValueError("Invalid value for `weigh_heaviness`, must not be `None`")  # noqa: E501

        self._weigh_heaviness = weigh_heaviness
