# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.period import Period  # noqa: F401,E501
from swagger_server import util


class Workout(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, element_type: str='period', period_range: str=None, period_type: str='workout', period_description: str='', workout_type: str=None):  # noqa: E501
        """Workout - a model defined in Swagger

        :param element_type: The element_type of this Workout.  # noqa: E501
        :type element_type: str
        :param period_range: The period_range of this Workout.  # noqa: E501
        :type period_range: str
        :param period_type: The period_type of this Workout.  # noqa: E501
        :type period_type: str
        :param period_description: The period_description of this Workout.  # noqa: E501
        :type period_description: str
        :param workout_type: The workout_type of this Workout.  # noqa: E501
        :type workout_type: str
        """
        self.swagger_types = {
            'element_type': str,
            'period_range': str,
            'period_type': str,
            'period_description': str,
            'workout_type': str
        }

        self.attribute_map = {
            'element_type': 'element_type',
            'period_range': 'period_range',
            'period_type': 'period_type',
            'period_description': 'period_description',
            'workout_type': 'workout_type'
        }
        self._element_type = element_type
        self._period_range = period_range
        self._period_type = period_type
        self._period_description = period_description
        self._workout_type = workout_type

    @classmethod
    def from_dict(cls, dikt) -> 'Workout':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Workout of this Workout.  # noqa: E501
        :rtype: Workout
        """
        return util.deserialize_model(dikt, cls)

    @property
    def element_type(self) -> str:
        """Gets the element_type of this Workout.


        :return: The element_type of this Workout.
        :rtype: str
        """
        return self._element_type

    @element_type.setter
    def element_type(self, element_type: str):
        """Sets the element_type of this Workout.


        :param element_type: The element_type of this Workout.
        :type element_type: str
        """

        self._element_type = element_type

    @property
    def period_range(self) -> str:
        """Gets the period_range of this Workout.


        :return: The period_range of this Workout.
        :rtype: str
        """
        return self._period_range

    @period_range.setter
    def period_range(self, period_range: str):
        """Sets the period_range of this Workout.


        :param period_range: The period_range of this Workout.
        :type period_range: str
        """
        if period_range is None:
            raise ValueError("Invalid value for `period_range`, must not be `None`")  # noqa: E501

        self._period_range = period_range

    @property
    def period_type(self) -> str:
        """Gets the period_type of this Workout.


        :return: The period_type of this Workout.
        :rtype: str
        """
        return self._period_type

    @period_type.setter
    def period_type(self, period_type: str):
        """Sets the period_type of this Workout.


        :param period_type: The period_type of this Workout.
        :type period_type: str
        """

        self._period_type = period_type

    @property
    def period_description(self) -> str:
        """Gets the period_description of this Workout.


        :return: The period_description of this Workout.
        :rtype: str
        """
        return self._period_description

    @period_description.setter
    def period_description(self, period_description: str):
        """Sets the period_description of this Workout.


        :param period_description: The period_description of this Workout.
        :type period_description: str
        """

        self._period_description = period_description

    @property
    def workout_type(self) -> str:
        """Gets the workout_type of this Workout.


        :return: The workout_type of this Workout.
        :rtype: str
        """
        return self._workout_type

    @workout_type.setter
    def workout_type(self, workout_type: str):
        """Sets the workout_type of this Workout.


        :param workout_type: The workout_type of this Workout.
        :type workout_type: str
        """
        allowed_values = ["cardio", "hiit_legs", "hiit_arms", "hiit_abs", "yoga"]  # noqa: E501
        if workout_type not in allowed_values:
            raise ValueError(
                "Invalid value for `workout_type` ({0}), must be one of {1}"
                .format(workout_type, allowed_values)
            )

        self._workout_type = workout_type
